name: PHP Composer

on:
  push:
    branches: -main 
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12

      with:
        API_KEY: ${{secrets.API_KEY}}
        heroku_app_name: "cafehuertoapp"
        heroku_email: "moty5871@gmail.com"

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
